### PR TITLE
Upgrade Ruby

### LINKED ISSUE #137: Upgrade to Ruby 2.5.3
@maciej-szlosarczyk, @teadur  Any obstacles you are aware of?

### PR DESCRIPTION
**Pull request by artur-beljajev**
@maciej-szlosarczyk  You probably want to tune Docker config as well? You mentioned some issue, if I remember correctly...

Closes #137

### CODE REVIEW

**Comment by maciej-szlosarczyk** [comment]
Not tune, but create a custom image as we no longer can use the approved Ruby image for variety of reasons:

* There is no approved image of Ruby 2.5 with Jessie. There's a PR that dates back to February 2018, so it will not happen. https://github.com/docker-library/ruby/pull/189
* live registry is stuck on Jessie because of EPP and how it is set up with Apache on the same machine.
* Stretch drops postgres-client 9.4, we are stuck with it because upgrading to higher version changes how `pg_dump` and `pg_restore` work. We should sooner rather than later move to 9.6 if not for safety then to get `UPSERT` and parallel queries that came respectively in 9.5 and 9.6.

Anyway, there is extra work involved with this change now and going forward because now we/I have to maintain the docker images even for point releases.

**Comment by vohmar** [comment]
merge conflicts with master

**Comment by artur-beljajev** [comment]
Everything I wanted to merge to master until commit 7fd16c1e356edb2d12f7d923da0f4b6c37eeee04 (see above) is already in master. No idea why there are some additional commits from Georg are here...

I think we can just close this PR.

**Comment by teadur** [comment]
@artur-beljajev why not close it then ? the pull request is opened by you ?
As of i dont see the point in bouncing the pull request around i shall close it myself to save everyones time :)

**Pull request closed without merging**
