### PR TITLE
Add some missed locale files

### LINKED ISSUE #239: Language selection does not work
Rest-WHOIS has a language selection of et, en and ru, but selecting any of these results the same English output with the exception of show more button in the end for private registrations and contacting link  in the show more view.

We should provide complete translations for introduction, field names  and their content where applicable

### PR DESCRIPTION
**Pull request by yulgolem**
Closes #239 
Relies on and must be checked after deploy of https://github.com/internetee/registry/pull/1704 .

### CODE REVIEW

**Comment by vohmar** [comment]
for some reason i see working translation only on the initial search view all the results views are still English only.

image

**Comment by vohmar** [comment]
the disclaimer on the restrictions for use of the whois search results is still not translated:

image

et translation: Otsitulemusi ei tohi kasutada ärilistel, reklaami, ümber töötlemise, edasi levitamise, taaskasutuse, muutmise ega muul sarnasel eesmärgil.
ru: maybe you can help with that one

**Comment by yulgolem** [comment]
ru: 'Результаты поиска не могут быть использованы в коммерческих целях, включая, но не ограничиваясь, рекламу, рекомпиляцию, изменение формата, перераспределение либо переиспользование.'

**Comment by yulgolem** [comment]
image

Staging is ready to test. Depends on https://github.com/internetee/registry/pull/1704

**Pull request merged**
