### PR TITLE
Add search bar

### PR DESCRIPTION
**Pull request by artur-beljajev**

### CODE REVIEW

**Comment by artur-beljajev** [comment]
@vohmar Please re-test the entire app

**Comment by artur-beljajev** [comment]
@teadur or @ratM1n Notice updated config/application-example.yml

**Comment by maciej-szlosarczyk** [comment]
I guess this went a little bit overboard from what it originally was 😞 

image

**Comment by vohmar** [comment]
indeed - way more stuff in here than needed for the search bar functionality. Will try to avoid this kind of thing better.

**Pull request merged**
