### PR TITLE
Refactor before disclosable contact attributes

### PR DESCRIPTION
**Pull request by artur-beljajev**
Needed for https://github.com/internetee/registry/issues/992.

Test entire WHOIS app thoroughly.

Special attention to timezones and disclosed/undisclosed data.

### CODE REVIEW

**Comment by vohmar** [comment]
translations missing in est and rus.
also dates are missing in est and rus

image

**Comment by artur-beljajev** [comment]
@teadur @ratM1n Make sure you have `require_relative 'production'` in `staging.rb`.

**Comment by teadur** [comment]
@artur-beljajev yep thats how it's configured, the file comes from repo, not changed localy.

**Comment by artur-beljajev** [comment]
@teadur @ratM1n Is there any custom `staging.rb` or `production.rb`?

**Comment by artur-beljajev** [comment]
ok

**Comment by vohmar** [comment]
also contact data of organisation owned domain name is not disclosed after solving recaptcha. Names, emails and changed dates should be all revealed after successfully solving recaptcha.

image

**Pull request merged**
